//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: vulnerable
// ----------------------------------------------------------------------------
pub mod vulnerable {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for vulnerable
    pub fn program_id() -> Pubkey {
        pubkey!("Gb1FA4kQRi5Ci2kChRbg2f8pTaqcutyAbCDciQxFQUf2")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CreateUserAccount
    // ....................................................................

    /// Main instruction struct for CreateUserAccount
    pub struct CreateUserAccountInstruction {
        pub accounts: CreateUserAccountInstructionAccountMetas,
        pub data: CreateUserAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateUserAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateUserAccountInstructionAccountMetas {
        pub user: AccountMeta,

        pub user_account: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateUserAccount instruction
    #[derive(Debug, Clone)]
    pub struct CreateUserAccountInstructionAccounts {
        pub user: Pubkey,

        pub user_account: Pubkey,
    }

    impl CreateUserAccountInstructionAccounts {
        pub fn new(user: Pubkey, user_account: Pubkey) -> Self {
            Self { user, user_account }
        }
    }

    /// Instruction data for CreateUserAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateUserAccountInstructionData {}

    impl CreateUserAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreateUserAccountInstruction
    impl CreateUserAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [146u8, 68u8, 100u8, 69u8, 63u8, 46u8, 182u8, 199u8]
        }

        pub fn data(data: CreateUserAccountInstructionData) -> Self {
            Self {
                accounts: CreateUserAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateUserAccountInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.user_account = AccountMeta::new(accounts.user_account, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.user_account.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Deposit
    // ....................................................................

    /// Main instruction struct for Deposit
    pub struct DepositInstruction {
        pub accounts: DepositInstructionAccountMetas,
        pub data: DepositInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Deposit instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositInstructionAccountMetas {
        pub user: AccountMeta,

        pub user_account: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Deposit instruction
    #[derive(Debug, Clone)]
    pub struct DepositInstructionAccounts {
        pub user: Pubkey,

        pub user_account: Pubkey,

        pub vault: Pubkey,
    }

    impl DepositInstructionAccounts {
        pub fn new(user: Pubkey, user_account: Pubkey, vault: Pubkey) -> Self {
            Self {
                user,

                user_account,

                vault,
            }
        }
    }

    /// Instruction data for Deposit
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositInstructionData {
        pub amount: u64,
    }

    impl DepositInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositInstruction
    impl DepositInstruction {
        fn discriminator() -> [u8; 8] {
            [242u8, 35u8, 198u8, 137u8, 82u8, 225u8, 242u8, 182u8]
        }

        pub fn data(data: DepositInstructionData) -> Self {
            Self {
                accounts: DepositInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.user_account = AccountMeta::new(accounts.user_account, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.user_account.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeVault
    // ....................................................................

    /// Main instruction struct for InitializeVault
    pub struct InitializeVaultInstruction {
        pub accounts: InitializeVaultInstructionAccountMetas,
        pub data: InitializeVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeVaultInstructionAccountMetas {
        pub authority: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeVault instruction
    #[derive(Debug, Clone)]
    pub struct InitializeVaultInstructionAccounts {
        pub authority: Pubkey,

        pub vault: Pubkey,
    }

    impl InitializeVaultInstructionAccounts {
        pub fn new(authority: Pubkey, vault: Pubkey) -> Self {
            Self { authority, vault }
        }
    }

    /// Instruction data for InitializeVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeVaultInstructionData {
        pub amount: u64,
    }

    impl InitializeVaultInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for InitializeVaultInstruction
    impl InitializeVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 191u8, 163u8, 44u8, 71u8, 129u8, 63u8, 164u8]
        }

        pub fn data(data: InitializeVaultInstructionData) -> Self {
            Self {
                accounts: InitializeVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeVaultInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub user: AccountMeta,

        pub user_account: AccountMeta,

        pub owner: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub user: Pubkey,

        pub user_account: Pubkey,

        pub owner: Pubkey,

        pub vault: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(user: Pubkey, user_account: Pubkey, owner: Pubkey, vault: Pubkey) -> Self {
            Self {
                user,

                user_account,

                owner,

                vault,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {
        pub amount: u64,
    }

    impl WithdrawInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.user_account = AccountMeta::new(accounts.user_account, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.user_account.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: UserAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UserAccount {
    pub owner: Pubkey,

    pub balance: u64,
}

impl UserAccount {
    pub fn new(owner: Pubkey, balance: u64) -> Self {
        Self { owner, balance }
    }
}

/// Custom struct: Vault
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Vault {
    pub authority: Pubkey,

    pub total_deposits: u64,
}

impl Vault {
    pub fn new(authority: Pubkey, total_deposits: u64) -> Self {
        Self {
            authority,

            total_deposits,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
