//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: escrow
// ----------------------------------------------------------------------------
pub mod escrow {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for escrow
    pub fn program_id() -> Pubkey {
        pubkey!("escrWWM1M3eA87HpqPuy7g2jEqZudP413zUa1m4oA2w")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CancelEscrow
    // ....................................................................

    /// Main instruction struct for CancelEscrow
    pub struct CancelEscrowInstruction {
        pub accounts: CancelEscrowInstructionAccountMetas,
        pub data: CancelEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelEscrowInstructionAccountMetas {
        pub canceller: AccountMeta,

        pub escrow: AccountMeta,

        pub vault: AccountMeta,

        pub depositor: AccountMeta,
    }

    /// Account pubkeys for CancelEscrow instruction
    #[derive(Debug, Clone)]
    pub struct CancelEscrowInstructionAccounts {
        pub canceller: Pubkey,

        pub escrow: Pubkey,

        pub vault: Pubkey,

        pub depositor: Pubkey,
    }

    impl CancelEscrowInstructionAccounts {
        pub fn new(canceller: Pubkey, escrow: Pubkey, vault: Pubkey, depositor: Pubkey) -> Self {
            Self {
                canceller,

                escrow,

                vault,

                depositor,
            }
        }
    }

    /// Instruction data for CancelEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelEscrowInstructionData {}

    impl CancelEscrowInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelEscrowInstruction
    impl CancelEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [156u8, 203u8, 54u8, 179u8, 38u8, 72u8, 33u8, 21u8]
        }

        pub fn data(data: CancelEscrowInstructionData) -> Self {
            Self {
                accounts: CancelEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelEscrowInstructionAccounts) -> Self {
            self.accounts.canceller = AccountMeta::new(accounts.canceller, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.depositor = AccountMeta::new(accounts.depositor, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.canceller.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.depositor.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Exchange
    // ....................................................................

    /// Main instruction struct for Exchange
    pub struct ExchangeInstruction {
        pub accounts: ExchangeInstructionAccountMetas,
        pub data: ExchangeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Exchange instruction
    #[derive(Debug, Clone, Default)]
    pub struct ExchangeInstructionAccountMetas {
        pub taker: AccountMeta,

        pub escrow: AccountMeta,

        pub vault: AccountMeta,
    }

    /// Account pubkeys for Exchange instruction
    #[derive(Debug, Clone)]
    pub struct ExchangeInstructionAccounts {
        pub taker: Pubkey,

        pub escrow: Pubkey,

        pub vault: Pubkey,
    }

    impl ExchangeInstructionAccounts {
        pub fn new(taker: Pubkey, escrow: Pubkey, vault: Pubkey) -> Self {
            Self {
                taker,

                escrow,

                vault,
            }
        }
    }

    /// Instruction data for Exchange
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ExchangeInstructionData {}

    impl ExchangeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ExchangeInstruction
    impl ExchangeInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 3u8, 27u8, 97u8, 215u8, 236u8, 219u8, 144u8]
        }

        pub fn data(data: ExchangeInstructionData) -> Self {
            Self {
                accounts: ExchangeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ExchangeInstructionAccounts) -> Self {
            self.accounts.taker = AccountMeta::new(accounts.taker, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.taker.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.vault.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FundEscrow
    // ....................................................................

    /// Main instruction struct for FundEscrow
    pub struct FundEscrowInstruction {
        pub accounts: FundEscrowInstructionAccountMetas,
        pub data: FundEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FundEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct FundEscrowInstructionAccountMetas {
        pub depositor: AccountMeta,

        pub escrow: AccountMeta,

        pub vault: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for FundEscrow instruction
    #[derive(Debug, Clone)]
    pub struct FundEscrowInstructionAccounts {
        pub depositor: Pubkey,

        pub escrow: Pubkey,

        pub vault: Pubkey,
    }

    impl FundEscrowInstructionAccounts {
        pub fn new(depositor: Pubkey, escrow: Pubkey, vault: Pubkey) -> Self {
            Self {
                depositor,

                escrow,

                vault,
            }
        }
    }

    /// Instruction data for FundEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FundEscrowInstructionData {
        pub amount: u64,
    }

    impl FundEscrowInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for FundEscrowInstruction
    impl FundEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [155u8, 18u8, 218u8, 141u8, 182u8, 213u8, 69u8, 201u8]
        }

        pub fn data(data: FundEscrowInstructionData) -> Self {
            Self {
                accounts: FundEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FundEscrowInstructionAccounts) -> Self {
            self.accounts.depositor = AccountMeta::new(accounts.depositor, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.depositor.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeEscrow
    // ....................................................................

    /// Main instruction struct for InitializeEscrow
    pub struct InitializeEscrowInstruction {
        pub accounts: InitializeEscrowInstructionAccountMetas,
        pub data: InitializeEscrowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeEscrow instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeEscrowInstructionAccountMetas {
        pub depositor: AccountMeta,

        pub escrow: AccountMeta,

        pub counterparty: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeEscrow instruction
    #[derive(Debug, Clone)]
    pub struct InitializeEscrowInstructionAccounts {
        pub depositor: Pubkey,

        pub escrow: Pubkey,

        pub counterparty: Pubkey,
    }

    impl InitializeEscrowInstructionAccounts {
        pub fn new(depositor: Pubkey, escrow: Pubkey, counterparty: Pubkey) -> Self {
            Self {
                depositor,

                escrow,

                counterparty,
            }
        }
    }

    /// Instruction data for InitializeEscrow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeEscrowInstructionData {
        pub amount: u64,
    }

    impl InitializeEscrowInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for InitializeEscrowInstruction
    impl InitializeEscrowInstruction {
        fn discriminator() -> [u8; 8] {
            [243u8, 160u8, 77u8, 153u8, 11u8, 92u8, 48u8, 209u8]
        }

        pub fn data(data: InitializeEscrowInstructionData) -> Self {
            Self {
                accounts: InitializeEscrowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeEscrowInstructionAccounts) -> Self {
            self.accounts.depositor = AccountMeta::new(accounts.depositor, true);

            self.accounts.escrow = AccountMeta::new(accounts.escrow, false);

            self.accounts.counterparty = AccountMeta::new_readonly(accounts.counterparty, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.depositor.clone());

            metas.push(self.accounts.escrow.clone());

            metas.push(self.accounts.counterparty.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: EscrowState
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct EscrowState {
    pub depositor: Pubkey,

    pub counterparty: Pubkey,

    pub amount: u64,

    pub status: u8,

    pub bump: u8,
}

impl EscrowState {
    pub fn new(depositor: Pubkey, counterparty: Pubkey, amount: u64, status: u8, bump: u8) -> Self {
        Self {
            depositor,

            counterparty,

            amount,

            status,

            bump,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
